version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/communityvi-frontend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/communityvi-server/"
    schedule:
      interval: "daily"

