version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/communityvi-frontend/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "cargo"
    directory: "/communityvi-server/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

