[package]
name = "communityvi-server"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>", "Thomas Keppler <winfr34k@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.30"
base64 = "0.12"
chrono = {version = "0.4", features = ["serde"]}
dashmap = "3.11"
env_logger = "0.7"
futures = "0.3"
gotham = {git = "https://github.com/communityvi/gotham", branch = "feature/fix-websockets", default-features = false}
log = "0.4"
mime = "0.3"
parking_lot = "0.10"
pin-project = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sha1 = "0.6"
structopt = "0.3"
tokio = { version = "0.2", features = ["rt-core", "rt-threaded", "time", "parking_lot", "macros", "sync"] }
tokio-tungstenite = "0.10"
toml = "0.5"
unicode_skeleton = "0.1"

[dev-dependencies]
lazy_static = "1.4"
