[package]
name = "communityvi-server"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>", "Thomas Keppler <winfr34k@gmail.com>"]
edition = "2018"
repository = "https://github.com/communityvi/communityvi"
resolver = "2"

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.13"
chrono = {version = "0.4", features = ["serde"]}
env_logger = "0.9"
futures = "0.3"
gotham = {git = "https://github.com/gotham-rs/gotham", default-features = false, features = ["derive"]}
governor = {version = "0.3", default-features = false, features = ["std", "jitter"]}
humantime-serde = "1.0"
log = "0.4"
mime = "0.3"
nonzero_ext = "0.3"
parking_lot = "0.11"
pin-project = "1"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sha1 = "0.6"
clap = "3.0.0-beta.4"
tokio = {version = "1", features = ["rt", "rt-multi-thread", "time", "parking_lot", "macros", "sync"]}
tokio-stream = {version = "0.1", features = ["sync"]}
tokio-tungstenite = "0.15"
toml = "0.5"
typed-builder = "0.9"
unicode_skeleton = "0.1"

[dev-dependencies]
rand = "0.8"

[build-dependencies]
npm_rs = "0.1"

[features]
default = []
bundle-frontend = []
