[package]
name = "communityvi-server"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>"]
edition = "2018"

[dependencies]
communityvi-lib = {path = "../communityvi-lib"}
futures = { version = "0.3.1", features = ["compat"] }
tokio-compat = "0.1.2"
