[package]
name = "communityvi-server"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>", "Thomas Keppler <winfr34k@gmail.com>"]
edition = "2021"
repository = "https://github.com/communityvi/communityvi"

[workspace]
members = [".", "hyper-test"]

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = {version = "3.1.5", features = ["derive"]}
env_logger = "0.9"
futures-util = "0.3.19"
futures-channel = "0.3.21"
governor = { version = "0.4", default-features = false, features = ["std", "jitter"] }
hex = '0.4'
humantime-serde = "1.0"
hyper-test = {path = "hyper-test"}
js_int = {git = "https://github.com/ruma/js_int", branch = "main", features = ["serde", "float_deserialize"]}
lazy_static = "1"
log = "0.4"
mime = "0.3"
mime_guess = {version = "2", default-features = false}
nonzero_ext = "0.3"
parking_lot = "0.12"
pin-project = "1"
rust-embed = { version = "6", features = ["interpolate-folder-path"] }
rust-embed5 = {package = "rust-embed", version = "5", optional = true}
rweb = { version = "0.15", default-features = false, features = ["openapi", "websocket"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
swagger-ui = {version = "0.1", optional = true}
thiserror = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "parking_lot", "macros", "sync"] }
tokio-stream = { version = "0.1", default-features = false, features = ["sync"] }
tokio-tungstenite = "0.16"
toml = "0.5"
typed-builder = "0.10"
unicode_skeleton = "0.1"

[dev-dependencies]
rand = "0.8"
async-trait = "0.1.52"
hyper-test = {path = "hyper-test"}

[build-dependencies]
npm_rs = "0.2"
ignore = "0.4.18"

[features]
default = ["api-docs"]
bundle-frontend = []
api-docs = ["rust-embed5", "swagger-ui"]
