[package]
name = "communityvi-server"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>"]
edition = "2018"

[dependencies]
config = "0.10"
log = "0.4"
env_logger = "0.7"
warp = "0.2"
futures = "0.3"
tokio = { version = "0.2", features = ["rt-core", "rt-threaded", "time", "parking_lot", "macros"] }
http = "0.2"
chrono = {version = "0.4", features = ["serde"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
contrie = "0.1"

[dev-dependencies]
reqwest = {version = "0.10", features = ["json"]}
tokio-tungstenite = { git = "https://github.com/snapview/tokio-tungstenite", rev = "master" }
url = "2.1"
parking_lot = "0.10"
lazy_static = "1.4"
