name: Backend
on:
  push:
    paths:
      - 'communityvi-server/**'
      - '.github/workflows/backend.yaml'
defaults:
  run:
    # The backend project is not in the repository root
    working-directory: ./communityvi-server
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install NodeJS
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18.x
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.83
      - uses: Swatinem/rust-cache@v2.7.5
        with:
          workspaces: "communityvi-server"
      - name: Check
        run: cargo check --all
      - name: Check without defaults
        run: cargo check --all --no-default-features
      - name: Check api-docs
        run: cargo check --all --features api-docs
      - name: Check bundle-frontend
        run: cargo check --all --features bundle-frontend
      - name: Check all features
        run: cargo check --all --all-features
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.83
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2.7.5
        with:
          workspaces: "communityvi-server"
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --tests -- -Dwarnings
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Install NodeJS
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18.x
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@1.83
      - uses: Swatinem/rust-cache@v2.7.5
        with:
          workspaces: "communityvi-server"
      - name: Build
        run: cargo build --all
      - name: Run tests
        run: cargo test --all
      - name: Run tests with bundled frontend and api-docs
        run: cargo test --all --features bundle-frontend,api-docs
