name: Frontend
on:
  push:
    paths:
      - 'communityvi-frontend/**'
      - '.github/workflows/frontend.yaml'
defaults:
  run:
    # The frontend project is not in the repository root
    working-directory: ./communityvi-frontend
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install NodeJS
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
      - name: Install packages
        run: npm install
      - name: ESLint & Prettier & Svelte check
        run: npm run lint
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install NodeJS
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
      - name: Install packages
        run: npm install
      - name: Build static files
        run: npm run build
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install NodeJS
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
      - name: Install packages
        run: npm install
      - name: Test
        run: npm run test
